server:
  port: 8081

ollama:
  host: ${OLLAMA_HOST:localhost}
  port: ${OLLAMA_PORT:11434}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

spring:
  application:
    name: inventory-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
      hibernate:
        ddl-auto: validate  # Solo valida que las entidades coincidan con la BD, no toca nada
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    enabled: true         # Habilita Flyway para gestionar los scripts SQL
    baseline-on-migrate: true # Permite que Flyway cree una línea base si la BD ya tiene datos

 # security:
 #   oauth2:
 #     resourceserver:
 #       jwt:
 #         issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health, info # Activa los Actuator endpoints para health checks en Docker
  endpoint:
    health:
      show-details: always